import { precacheAndRoute } from "workbox-precaching";

// manifest import will be autogenerated by webpack
precacheAndRoute(self.__WB_MANIFEST || []);
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDKWorker.js');
