// import { precacheAndRoute } from "workbox-precaching";

// // manifest import will be autogenerated by webpack
// precacheAndRoute(self.__WB_MANIFEST || []);

// self.addEventListener('message', function(event) {
//     if (event.data.action === 'skipWaiting') {
//         self.skipWaiting();
//     }
// });

// self.addEventListener('push', function (event) {
//     console.log('[Service Worker] Push Received.');
//     console.log(`[Service Worker] Push had this data: "${event.data.text()}"`);
//     let x = event.data.text();

//     const title = 'Doctorize';
//     const options = {
//         body: event.data.text(),
//         icon: 'images/icon.png',
//         badge: 'images/badge.png'
//     };
//     event.waitUntil(self.registration.showNotification(title, options));
// });

this.importScripts('https://cdn.onesignal.com/sdks/OneSignalSDKWorker.js');
