import { precacheAndRoute } from "workbox-precaching";

// manifest import will be autogenerated by webpack
precacheAndRoute(self.__WB_MANIFEST || []);

self.addEventListener("message", function (event) {
	if (event.data.action === "skipWaiting") {
		self.skipWaiting();
	}
});

self.addEventListener("push", function (event) {
	console.log("[Service Worker] Push Received.");
	console.log(`[Service Worker] Push had this data: "${event.data.text()}"`);
	// Notification.requestPermission(function (result) {
	// 	if (result === "denied") {
	// 		console.log("Permission wasn't granted. Allow a retry.");
	// 		return;
	// 	} else if (result === "default") {
	// 		console.log("The permission request was dismissed.");
	// 		return;
	// 	}

		const title = "Push Codelab";
		const options = {
			body: "Yay it works.",
			icon: "images/icon.png",
			badge: "images/badge.png",
		};

		event.waitUntil(self.registration.showNotification(title, options));
	// });
	// event.waitUntil(app.);
});
